tasks:
  - init: ./gradlew build

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

    - vscjava.vscode-java-debug
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-test
